inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/*.rb'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/config.ru'
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'

  # Cop names are not displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the -D/--display-cop-names
  # option.
  DisplayCopNames: true

  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding DisplayStyleGuide, or by giving the
  # -S/--display-style-guide option.
  DisplayStyleGuide: true

Style/NumericLiterals:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

# Align with the style guide.
Style/CollectionMethods:
  Enabled: true

  # Mapping from undesired method to desired_method
  # e.g. to use `detect` over `find`:
  #
  # CollectionMethods:
  #   PreferredMethods:
  #     find: detect
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/ConditionalAssignment:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  Enabled: false

Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: true

Style/WordArray:
  Enabled: true
  MinSize: 4
