:max_retries: 3
:queues:
  - default
  - accounting
  - orders
  - reporting
:schedule:
  daily_sales_receipts:
    cron: '0 9 * * *'
    class: 'DailySalesReceipts'
    description: 'Report accounting to QBO and App'
  update_product_costs:
    cron: '0 8 * * *'
    class: 'UpdateProductCosts'
    description: 'Update product costs from shopify before sales receipts'
  daily_ordering:
    cron: '0 10 * * 1-5'
    class: 'DailyOrdering'
    description: 'Daily Orders for shops (restocks from warehouse)'
  barcode_issues_check:
    cron: '0 17 * * 1-5'
    class: 'BarcodeIssuesCheck'
    description: 'Check for duplicated and deleted shopify products'
