:max_retries: 3
:queues:
  - default
  - accounting
  - orders
  - reporting
:schedule:
  sku_check:
    cron: '0 21 * * *'
    class: 'SkuCheck'
    description: 'Check for mismatched SKUs'
  daily_sales_receipts:
    cron: '0 9 * * *'
    class: 'DailySalesReceipts'
    description: 'Report accounting to QBO and App'
  renew_sos_token:
    cron: '* * 1 * *'
    class: 'RenewSosToken'
    description: 'Refresh SOS access token once a month'
  update_product_costs:
    cron: '0 8 * * *'
    class: 'UpdateProductCosts'
    description: 'Update product costs from shopify before sales receipts'
