max_retries: 3
:queues:
  - accounting
  - default
  - orders
:schedule:
  sku_check:
    cron: '0 21 * * *'
    class: 'SkuCheck'
    description: 'Check for mismatched SKUs'
  daily_sales_receipts:
    cron: '0 9 * * *'
    class: 'DailySalesReceipts'
    description: 'Report accounting to QBO and App'
  # daily_ordering:
  #   cron: '00 12 * * MON,WED,FRI'
  #   class: 'DailyOrdering'
  #   description: 'Daily Orders for inventory transfers'
